### ISSUE TITLE
Trojan.Gen.2

### ISSUE THREAD

**Issue by EAR95** [simennj/itsdownloading#7]
Hi! 

I'm trying to run "itsdownloading.exe", but my Norton antivirus isolates the program due to an occurence of "Trojan.Gen.2", saying the file contains a virus. Why am I getting this message?

**Comment by simennj** [comment]
Standalone executables created from python files have a tendency to get false positives as a trojan on some antivirus softwares. I have submitted a sample to Norton, in the meantime i would recommend running the python script directly or switching antivirus software.

As for the "why": It is because they don't actually get compiled into a single binary, the python files are packed into the .exe file together with the python binaries and libraries used. To be run the .exe file has to self extract some files to a temporary location, a behavior that some antivirus software falsely detects as malicious. This is, by the way, the reason why the files are so large even though the actual script is only 11KiB. It has to include both a standalone python executable and the libraries used in addition to the script.

**Comment by EAR95** [comment]
Okey, I understand :) Thank you!

**Comment by simennj** [comment]
V1.3.3 should be whitelisted by Norton now (you may have to update Norton first). The new v1.3.4 should be whitelisted by tomorrow. Please report back if Norton still tries to isolate it.

**Comment by EAR95** [comment]
V1.3.3 worked great now! 👍 Thank you!
